# -*- coding: utf-8 -*-
"""Graficos/tabelas_Lista_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TMbOgoPNLQbqC-sgYAjc9hSLyyQ6z9_6

# Bibliotecas
"""

import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
import turtle
import os

"""# Dados"""

endereco = 'C:/Users/Patinete_do_Robertin/Desktop/lista 2/'

d_rota        = pd.read_csv(endereco+'resultados/djibout/djibout_out_tour.csv')

#l_rota        =  pd.read_csv('/content/drive/My Drive/Metaheurística/Dados Lista 2/aqui/Luxemburgo_out_tour.csv')

#o_rota        = pd.read_csv('/content/drive/My Drive/Metaheurística/Dados Lista 2/aqui/Omã_MaxMin_out_tour.csv')


"""#Mapa"""

rota1 = pd.read_csv(endereco+'djibout.csv')
#rota2 = pd.read_csv('/content/drive/My Drive/Metaheurística/Dados Lista 2/Luxemburgo.csv')
#rota3 = pd.read_csv('/content/drive/My Drive/Metaheurística/Dados Lista 2/Omã.csv')

location1 = list(zip(rota1['x']/1000, rota1['y']/1000))
#location2 = list(zip(rota2['x']/1000, rota1['y']/1000))
#location3 = list(zip(rota3['x']/1000, rota1['y']/1000))

plot_d = list(d_rota['ACS_tour_dist'])
#plot_l = list(l_rota['Elitist_tour_dist'])
# #plot_o = list(o_rota['MaxMin_tour_dist'])
route = plot_d

#*********************************************************
# import turtle
# from os import path
# #WARNING: IMAGES MUST BE .GIF
# currentDir = os.abspath(path.curdir) #get the python file location

# wn = turtle.Screen()
# wn.setup(width=700,height=400)
# wn.title("image test")

# wn.addshape(currentDir+"\\Resources\\image.gif") #u can make images in a new folder

# myImage = turtle.Turtle()
# myImage.speed(0) #so it will draw the image instantly
# myImage.shape(currentDir+"\\Resources\\image.gif") #give your object the image
# myImage.penup() #if you dont do this, it will draw a line
# myImage.goto(0,0) #give your image a location

# while True:
#   wn.update() #update your window

# from sklearn.preprocessing import MinMaxScaler
#*********************************************************

currentDir = "png_carro.gif"
location = np.array(location1) 
route = plot_d

scaler = MinMaxScaler(feature_range=(-163, 150))
location[:, 1] = scaler.fit_transform(location[:, 1].reshape(-1, 1)).reshape(1, -1)
scaler = MinMaxScaler(feature_range=(-81, 84))
location[:, 0] = scaler.fit_transform(location[:, 0].reshape(-1, 1)).reshape(1, -1)

_nodes = location
screen = turtle.Screen()
screen.setup(1024, 1104)
screen.title("image test")

screen.addshape(currentDir)
screen.setworldcoordinates(-180, -90, 180, 90)
screen.bgpic(endereco+'t.png')


loc = turtle.Turtle(currentDir)
# sleep(10)
loc.shape('circle')
loc.color('green')
loc.shape(currentDir)
loc.penup()
start = _nodes[route[0]]
loc.goto(*start[::-1])

loc.dot(30)
loc.color('blue')
loc.pendown()
for idx in route[1:len(route)-1]:
    [lat, lon] = _nodes[idx]
    loc.goto(lon, lat)
    loc.dot(5)

end = _nodes[route[len(route)-1]]
loc.goto(*end[::-1])
loc.speed(0)
loc.color('red')
loc.dot(30)
loc.hideturtle()
screen.exitonclick()


